apiVersion: apps/v1
kind: Job
metadata:
  name: cicd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      deployment: hello
  template:
    metadata:
      labels:
        deployment: hello
    spec:
      containers:
      - name: hello-world
        image: gcr.io/omega-research-321011/hello-world
        
