apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      deployment: hello
  template:
    metadata:
      labels:
        deployment: hello
    spec:
      containers:
      - name: the-container
        image: gcr.io/omega-research-321011/hello_world
        
