apiVersion: batch/v1
kind: Job
metadata:
  name: cicd-deployment
spec:
  template:      
    spec:
      containers:
      - name: hello-fresh
        image: gcr.io/omega-research-321011/hello-fresh
      restartPolicy: Never
  backoffLimit: 4
        
